// app/components/Navigation.tsx
import { Link } from "@remix-run/react";
import React from "react";

function Navigation() {
  return (
    <>
      <nav className="flex justify-end mr-4 py-5">
        <Link
          to="/"
          className="text-lg text-primary font-medium hover:text-secondary active:underline"
        >
          Home
        </Link>
        <Link
          to="/portfolio"
          className="mx-4 text-lg text-primary font-medium  hover:text-secondary"
        >
          Projects
        </Link>
        <Link
          to="/blog"
          className="text-primary text-lg font-medium hover:text-secondary mr-4"
        >
          Blog
        </Link>
      </nav>
    </>
  );
}

export default Navigation;

// src/components/Navigation/Navigation.vue
<template>
    <nav class="Navigation lg:flex flex-grow items-center">
      <ul class='flex flex-col lg:flex-row list-none ml-auto'>
        <li class='nav-item'>
          <g-link to='/' class='px-3 py-2 flex text-sm uppercase font-bold leading-snug'>Home</g-link>
        </li>
        <li>
          <g-link to='/projects' class='px-3 py-2 flex text-sm uppercase font-bold leading-snug'>Work</g-link>
        </li>
        <li>
          <g-link to='/blog' class='px-3 py-2 flex text-sm uppercase font-bold leading-snug'>Blog</g-link>
        </li>
      </ul>
    </nav>
</template>

<script>
    export default {
        name: 'Navigation'
    };
</script>
